create database hostel;


CREATE TABLE Mess(Mess_ID INT NOT NULL, MName VARCHAR(20), Capacity INT NOT NULL, Veg_NonVeg CHAR, PRIMARY KEY(Mess_ID)); 

CREATE TABLE Room(Room_ID INT NOT NULL,Room_Type_Sharing INT NOT NULL, Attached_Bath CHAR, PRIMARY KEY(Room_ID)); 

CREATE TABLE Block(Block_ID INT NOT NULL, BName VARCHAR(4), No_of_Rooms INT NOT NULL, Capacity INT NOT NULL, PRIMARY KEY(Block_ID)); 

CREATE TABLE Department(Dept_ID INT NOT NULL,DName VARCHAR(25) NOT NULL, No_of_Emp INT NOT NULL, PRIMARY KEY(Dept_ID)); 


CREATE TABLE Student(Fname VARCHAR(15) NOT NULL, Minit CHAR, Lname VARCHAR(15) NOT NULL, SRN VARCHAR(13) NOT NULL, DOB DATE, Addr VARCHAR(30), Sex CHAR, Email VARCHAR(30), CGPA DECIMAL(3,2), Fees DECIMAL(10,2), Attendance DECIMAL(4,2), Mess_ID INT NOT NULL, Room_ID INT NOT NULL, PRIMARY KEY(SRN), FOREIGN KEY (Mess_ID) REFERENCES Mess(Mess_ID), FOREIGN KEY (Room_ID) REFERENCES Room(Room_ID));

CREATE TABLE Employee(Fname VARCHAR(15) NOT NULL, Minit CHAR, Lname VARCHAR(15) NOT NULL, Aadhaar NUMERIC(12,0) NOT NULL, DOB DATE, Addr VARCHAR(30), Sex CHAR, Salary DECIMAL(10,2), Super_ID NUMERIC(12,0) NOT NULL, Mess_ID INT NOT NULL, D_ID INT NOT NULL, PRIMARY KEY(Aadhaar), FOREIGN KEY (Mess_ID) REFERENCES Mess(Mess_ID), FOREIGN KEY (Super_ID) REFERENCES Employee(Aadhaar), FOREIGN KEY (D_ID) REFERENCES Department(Dept_ID));

CREATE TABLE Parent(SRN VARCHAR(13) NOT NULL,Fname VARCHAR(15) NOT NULL, Minit CHAR, Lname VARCHAR(15) NOT NULL,Addr VARCHAR(30),Email VARCHAR(30),Occupation VARCHAR(10), PRIMARY KEY(SRN,Fname), FOREIGN KEY(SRN) REFERENCES Student(SRN));

CREATE TABLE Belongs_To(Block_ID INT NOT NULL,R_ID INT NOT NULL, PRIMARY KEY(Block_ID,R_ID), FOREIGN KEY(Block_ID) REFERENCES Block(Block_ID), FOREIGN KEY(R_ID) REFERENCES Room(Room_ID)); 

CREATE TABLE Student_Phone(Stu_ID VARCHAR(13),phone NUMERIC(10,0) NOT NULL, PRIMARY KEY(Stu_ID,phone), FOREIGN KEY(Stu_ID) REFERENCES Student(SRN)); 


CREATE TABLE Employee_Phone(Emp_ID NUMERIC(12,0),phone NUMERIC(10,0) NOT NULL, PRIMARY KEY(Emp_ID,phone), FOREIGN KEY(Emp_ID) REFERENCES Employee(Aadhaar)); 

 CREATE TABLE Parent_Phone(Stu_ID VARCHAR(13),Fname VARCHAR(15),phone NUMERIC(10,0) NOT NULL, PRIMARY KEY(Stu_ID,Fname,phone), FOREIGN KEY(Stu_ID,Fname) REFERENCES Parent(SRN,Fname)); 

